version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping upload package..."
      - zip -r backend.zip .
      - echo "Uploading lambda Function..."
      - aws lambda update-function-code --function-name mulberry --zip-file fileb://backend.zip
      - echo "DONE!"